### ISSUE TITLE
Make Error in Fedora 23

### ISSUE THREAD

**Issue by andrewmaurer** [ssfrr/AudioIO.jl#59]
Running Pkg.add("AudioIO") on Fedora 23 yields a make error. To remedy this you can run the command:
```
    sudo dnf install portaudio
```
Then launch Julia and reinstall / remake AudioIO

**Comment by ssfrr** [comment]
I'm not actively developing the portaudio functionality in AudioIO any more. That development has moved to [PortAudio.jl](http://www.github.com/JuliaAudio/PortAudio.jl). I haven't tested that package on a Fedora machine but would definitely appreciate if you're able to and file an issue there if it doesn't work. The BinDeps stuff in that package has been updated somewhat from what's here in AudioIO, so it may work.
